#pragma once

#include "ps2.h"
#include "monitor.h"

namespace Keyboard {
    enum class LEDState : u8 {
        ScrollLock = 1,
        NumberLock = 2,
        CapsLock = 4,
    };

    enum class Key : u8 {
        Escape,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        PrintScreen,
        ScrollLock,
        Pause,
        BackTick,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Zero,
        Minus,
        Equal,
        BackSpace,
        Tab,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        LeftBracket,
        RightBracket,
        BackSlash,
        CapsLock,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        SemiColon,
        Apostrophe,
        Enter,
        LeftShift,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Comma,
        Period,
        Slash,
        RightShift,
        LeftControl,
        LeftSuper,
        LeftAlt,
        Space,
        RightAlt,
        Fn,
        RightSuper,
        RightControl,
        Insert,
        Home,
        PageUp,
        Delete,
        End,
        PageDown,
        Up,
        Left,
        Down,
        Right,
        NumLock,
        NumSlash,
        NumAsterisk,
        NumMinus,
        Num7,
        Num8,
        Num9,
        Num4,
        Num5,
        Num6,
        NumPlus,
        Num1,
        Num2,
        Num3,
        Num0,
        NumPeriod,
        NumEnter,
        WWWSearch,
        PreviousTrack,
        WWWFavorites,
        WWWRefresh,
        VolumeDown,
        Mute,
        WWWStop,
        Calculator,
        Apps,
        WWWForward,
        VolumeUp,
        PlayPause,
        Power,
        WWWBack,
        WWWHome,
        Stop,
        Sleep,
        MyComputer,
        Email,
        NextTrack,
        MediaSelect,
        Wake,

    };

    void init();
    void enableScanning();
    void disableScanning();
    bool setLed(LEDState state);
    bool echo();
    void setScanCodeSet(i8 code);
    i8 getScanCodeSet();
    void scan();
    bool keyPressed(Key key);
    void test();
    void setKey(Key key, bool enabled);
}